import rouletteBORD from "../../assets/images/thumbs_bg.webp";

export const style = {
  root: {
    maxWidth: "400px",
    width: "100%",
    backgroundColor: "#000000",
    height: "85vh",
    overflow: "hidden",
    marginTop: "auto",
    position: "relative",
    backgroundImage: `url(${rouletteBORD})`,
    backgroundSize: "100% 100%",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right",
    // transform: 'rotate(-90deg) !important',
    // left: '22% !important',
  },

  red: {
    "&>p": {
      background: "red",
      width: "80%",
      borderRadius: "60%",
      fontSize: "15px",
      fontWeight: 600,
      color: "white",
    },
  },
  black: {
    "&>p": {
      background: "black",
      width: "80%",
      borderRadius: "60%",
      fontSize: "15px",
      fontWeight: 600,
      color: "white",
    },
  },
  bettable: {
    width: "44%",
    height: "70%",
    position: "absolute",
    left: "30%",
    top: "2%",
  },
  btn1: {
    padding: 0,
    border: "1px solid white",
    // width: "20%",
    borderRadius: "0px",
    height: "100%",
    transform: "rotate(-180deg)",
    "&>p": {
      fontSize: "10px",
      fontWeight: 600,
      color: "white",
    },
  },
  btn2: {
    padding: 0,
    border: "1px solid white",
    // width: "33.33333%",
    borderRadius: "0px",
    // height: "25%",
    transform: "rotate(-180deg)",
  },
  btn3: {
    padding: 0,
    border: "1px solid white",
    // width: "100%",
    borderRadius: "0px",
    // fontSize: "10px",
    color: "white",
    fontWeight: 600,
    height: "100%",
    "&>p": {
      transform: "rotate(-270deg)",
      fontSize: "12px",
      fontWeight: 600,
      color: "white",
    },
  },
  btn4: {
    padding: 0,
    fontSize: "12px",
    fontWeight: 900,
    color: "white",
    position: "relative",
    left: "43%",
    background: "green",
    width: "20px",
    height: "20px",
    borderRadius: "50%",
    display: 'flex',
    alignItems: 'end',
    marginTop: '5px'
  },
  rotatingElement: { animation: "$rotateInfinite 4s linear infinite" },
  "@keyframes rotateInfinite": {
    "0%": { transform: "rotate(0deg)" },
    "100%": { transform: "rotate(360deg)" },
  },
  naiming: {
    background:
      "linear-gradient(to right,#BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C)",
    width: "100px",
    transform: "rotate(90deg)",
    position: "absolute",
    top: "5%",
    left: "-4%",
    borderRadius: "5px",
    "&>p:nth-child(1)": {
      color: "black",
      fontSize: "11px",
      fontWeight: "600",
      textAlign: "center",
    },
    "&>p:nth-child(2)": {
      color: "white",
      fontSize: "13px",
      fontWeight: "600",
      padding: "2px 2px",
      background: "#15158f",
      width: "80%",
      margin: "auto",
      marginBottom: "5px",
      borderRadius: "2px",
      textAlign: 'center',
    },
  },
  naiming2: {
    background:
      "linear-gradient(to right,#BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C)",
    width: "100px",
    transform: "rotate(90deg)",
    position: "absolute",
    top: "21%",
    left: "-4%",
    borderRadius: "5px",
    "&>p:nth-child(1)": {
      color: "black",
      fontSize: "13px",
      fontWeight: "600",
      textAlign: "center",
    },
    "&>p:nth-child(2)": {
      color: "white",
      fontSize: "11px",
      fontWeight: "600",
      padding: "2px 2px",
      background: "#15158f",
      width: "80%",
      margin: "auto",
      marginBottom: "5px",
      borderRadius: "2px",
      textAlign: 'center',
    },
  },
  naiming3: {
    background:
      "linear-gradient(to right,#BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C)",
    width: "80px",
    transform: "rotate(90deg)",
    position: "absolute",
    top: "51.5%",
    left: "-1.5%",
    borderRadius: "5px",
    // padding: "15px",
    "&>p:nth-child(1)": {
      color: "white",
      fontSize: "10px",
      fontWeight: "600",
      padding: "5px 5px",
      background: "#15158f",
      width: "80%",
      margin: "auto",
      marginBottom: "5px",
      borderRadius: "2px",
      textAlign: 'center',
    },

  },
  naiming4: {
    background: "red",
    width: "50px",
    transform: "rotate(90deg)",
    position: "absolute",
    bottom: "20%",
    left: "1%",
    borderRadius: "5px",
    padding: '5px 0px',
    "&>p:nth-child(1)": {
      color: "white",
      fontSize: "10px",
      background: "red",
      borderRadius: "2px",
      textAlign: 'center;'
    },
  },
  naiming7: {
    background: 'red',
    transform: "rotate(90deg)",
    position: "absolute",
    bottom: "30%",
    left: "-0.5%",
    padding: "10px 5px",
    borderRadius: "5px",
    "&>p:nth-child(1)": {
      color: "white",
      fontSize: "10px",
      fontWeight: "600",
      textAlign: "center",
    },
  },
  naiming5: {
    background: '#15158f',
    transform: "rotate(90deg)",
    position: "absolute",
    bottom: "25%",
    left: "5%",
    padding: "10px",
    borderRadius: "5px",
    "&>p:nth-child(1)": {
      color: "white",
      fontSize: "13px",
      fontWeight: "600",
      textAlign: "center",
    },
  },

  naiming6: {
    background:
      "linear-gradient(to right,#BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C)",
    width: "100px",
    transform: "rotate(90deg)",
    position: "absolute",
    top: "37%",
    left: "-4%",
    borderRadius: "5px",
    textAlign: "center",
    "&>p:nth-child(1)": {
      color: "white",
      fontSize: "10px",
      fontWeight: "600",
      padding: "5px 5px",
      background: "#15158f",
      width: "80%",
      margin: "auto",
      marginBottom: "5px",
      borderRadius: "2px",
      textAlign: 'center',
    },
  },
  countdownOuter: {
    position: "absolute",
    width: "75px",
    height: "75px",
    background: "black",
    bottom: "4%",
    left: "4%",
    border: "2px solid white",
    borderRadius: "10px",
    outline: "10px solid black",
    boxSizing: "border-box",
  },
  winnerlooserouter: {
    padding: "2px",
    border: "2px solid #C9A553",
    position: "absolute",
    right: "-2%",
    transform: "rotate(90deg)",
    top: "28%",
    width: "120px",
    borderRadius: "5px",
  },
  winnerlooserouter2: {
    padding: "2px",
    border: "2px solid #C9A553",
    position: "absolute",
    right: "0%",
    transform: "rotate(90deg)",
    top: "8%",
    width: "100px",
    borderRadius: "5px",
  },
  winnerlooserouter3: {
    padding: "2px",
    border: "2px solid #C9A553",
    position: "absolute",
    right: "2%",
    transform: "rotate(90deg)",
    top: "48%",
    width: "70px",
    height: "50px",
    borderRadius: "5px",
    background: "black",
  },
  winnerLooserList: {
    display: "flex",
    justifyContent: "space-around",
    width: "100%",
    "&>p:nth-child(1)": {
      fontSize: "12px",
      fontWeight: "900",
      color: "yellow",
    },
    "&>p:nth-child(2)": {
      fontSize: "12px",
      fontWeight: "900",
      color: "#90ff90",
    },
    "&>p:nth-child(3)": { fontSize: "12px", fontWeight: "900", color: "red" },
  },
  winnerLooserList2: {
    width: "100%",
    "&>p": {
      fontSize: "12px",
      fontWeight: "600",
      color: "yellow",
      textAlign: "center",
    },
  },
  winnerLooserList3: {
    width: "100%",
    "&>p": {
      fontSize: "35px",
      fontWeight: "600",
      color: "yellow",
      textAlign: "center",
    },
  },
  flex: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
};

